[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn article_flow.wsgi"
runtime = "V2"
healthcheckPath = "/"
healthcheckTimeout = 100
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10